"""Sentiment endpoint — GET /sentiment/{drama_name}."""

import pandas as pd
from fastapi import APIRouter, HTTPException, status

from src.api.schemas import SentimentResponse
from src.utils.config import settings
from src.utils.logger import get_logger

logger = get_logger("api.sentiment")

router = APIRouter(prefix="/sentiment", tags=["sentiment"])

_SENTIMENT_CSV = settings.paths.data_processed / "drama_sentiment.csv"

# Column name candidates
_NAME_COLS = ("title", "drama_name", "name")
_POLARITY_COLS = ("tb_polarity", "polarity")
_SUBJECTIVITY_COLS = ("tb_subjectivity", "subjectivity")
_LABEL_COLS = ("tb_label", "label", "sentiment_label")
_COUNT_COLS = ("review_count", "n_reviews", "count")


def _load_sentiment() -> pd.DataFrame:
    """Load drama-level sentiment CSV (empty DataFrame if not yet generated)."""
    if not _SENTIMENT_CSV.exists():
        return pd.DataFrame()
    return pd.read_csv(_SENTIMENT_CSV)


def _get_value(row: pd.Series, candidates: tuple, default):
    """Return the value of the first matching column, or *default*."""
    for col in candidates:
        if col in row.index and pd.notna(row[col]):
            return row[col]
    return default


@router.get("/{drama_name}", response_model=SentimentResponse)
async def get_sentiment(drama_name: str) -> SentimentResponse:
    """
    Return aggregated TextBlob sentiment scores for a drama.

    Sentiment data is generated by **scripts/run_sentiment.py**.
    This endpoint is public (no auth required).
    """
    df = _load_sentiment()
    if df.empty:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=("Sentiment data is not available. " "Run scripts/run_sentiment.py first."),
        )

    name_col = next((c for c in _NAME_COLS if c in df.columns), df.columns[0])
    key = drama_name.strip().lower()
    mask = df[name_col].str.strip().str.lower() == key
    matches = df[mask]

    if matches.empty:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"No sentiment data found for '{drama_name}'.",
        )

    row = matches.iloc[0]
    return SentimentResponse(
        drama_name=drama_name,
        polarity=float(_get_value(row, _POLARITY_COLS, 0.0)),
        subjectivity=float(_get_value(row, _SUBJECTIVITY_COLS, 0.0)),
        label=str(_get_value(row, _LABEL_COLS, "neutral")),
        review_count=int(_get_value(row, _COUNT_COLS, 0)),
    )
